name: Integration

on:
  workflow_dispatch:
  pull_request:

jobs:
  integrate:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests and capture logs
        id: tests
        continue-on-error: true  
        run: |
          mkdir -p test-results
          PYTHONPATH=backend pytest unit_tests/ --capture=tee-sys --cov=backend --cov-report=term --cov-report=html --junitxml=test-results/results.xml > test-results/results.log

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results/

      - name: Fail the job if tests failed
        if: steps.tests.outcome == 'failure'
        run: |
          echo "La suite de pruebas unitarias o de modelo ha fallado. Revisa el artefacto 'pytest-results' para ver los logs."
          exit 1